# Generated by Django 2.1.5 on 2019-01-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
